### ISSUE TITLE
v2.0.4 should be v3.X.X

### ISSUE THREAD

**Issue by rvh** [mesqueeb/copy-anything#12]
IMHO you can not break compatibility to a npm MAJOR version in a PATCH release. This forces all projects with npm <7 to update npm if they depend on a 'tilde' or 'hat' version of copy-anything.
See https://github.com/mesqueeb/copy-anything/blob/production/package.json#L22

**Comment by mesqueeb** [comment]
@rvh yeah makes sense. I will push another major update reverting back and then will make the major update

**Comment by mesqueeb** [comment]
@rvh I just pushed an update to undo some of the requirements. did it fix the issue for you?

**Comment by mesqueeb** [comment]
@rvh i will downgrade that dependency, please hold on

**Comment by mesqueeb** [comment]
@rvh how about now: v2.0.6 

<sub>--<br />copy-anything was made with 💜 by Luca Ban.<br />You cannot sponsor every project, but next time you do, think of <a href="https://github.com/sponsors/mesqueeb">this one</a> for its prolonged maintenance.</sub>

**Comment by rvh** [comment]
@mesqueeb Everything looks fine now! Thank you so much, also for your availability! Great job!
