### ISSUE TITLE
`main` module field that could not be resolved

### ISSUE THREAD

**Issue by jinshiyi11** [mesqueeb/copy-anything#22]
When using in **react-native**,I'm getting the following error:  

Error: While trying to resolve module `copy-anything` from file `D:\code\react\list_cache\node_modules\superjson\dist\index.js`, the package `D:\code\react\list_cache\node_modules\copy-anything\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`D:\code\react\list_cache\node_modules\copy-anything\dist\index.cjs`. Indeed, none of these files exist:

  * D:\code\react\list_cache\node_modules\copy-anything\dist\index.cjs(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * D:\code\react\list_cache\node_modules\copy-anything\dist\index.cjs\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)

**Comment by mesqueeb** [comment]
it's here though : )
https://github.com/mesqueeb/copy-anything/blob/production/dist/index.cjs

**Comment by jinshiyi11** [comment]
thanks，maybe it cause by config of my project.
