### ISSUE TITLE
Get types import error in node mode resolution

### ISSUE THREAD

**Issue by jaredhan418** [mesqueeb/copy-anything#26]
<img width="881" alt="截屏2024-07-04 15 41 04" src="https://github.com/mesqueeb/copy-anything/assets/11781874/b02530f7-d58f-4f9c-a832-1c5ad1812799">

**Comment by jaredhan418** [comment]
I am using this amazing lib in browser with Vite. Amazing to got a pure esm version but currently I can't set mode resolution to node16 in browser tsconfig.

**Comment by mesqueeb** [comment]
If you use an older node version, you can just stay on the previous major version.

Sorry but if I have to support older versions it's a tooling and maintenance hell for me and other issues will come up and create more work. 

The previous major version is perfectly fine to use so just use that one please.
