### ISSUE TITLE
Where is 2.0.1 tag?

### ISSUE THREAD

**Issue by mickaelistria** [mesqueeb/copy-anything#9]
I'd like to use https://www.npmjs.com/package/copy-anything 2.0.1 and need ClearlyDefined to contain more data about it at https://clearlydefined.io/definitions/npm/npmjs/-/copy-anything/2.0.1 . The main missing one is the source commit. I couldn't find a tag or a commit with 2.0.1 . Where can it be found?

**Comment by mesqueeb** [comment]
I don't make Github tags for all versions, only when there are significant changes.
Making tags on Github is a very manual and painly process. And I have like 20 libraries I constantly update, so it's not worth the effort.

You can always check the git commits on production, you'll find recent changes there:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/3253920/106900747-3c28c100-673a-11eb-97a5-f040ed0cda6d.png">


But as I said, if it's no new feature or anything, it's usually just bumping dependencies etc.

**Comment by mickaelistria** [comment]
Thanks. ClearlyDefined allows to reference specific commit.
However, I don't buy that `git tag 2.0.1 && git push myRepo 2.0.1` is such a painful process :P

**Comment by mesqueeb** [comment]
@mickaelistria I never knew about those commands. First time anyone ever taught them to me ><

**Comment by mesqueeb** [comment]
@mickaelistria your comments made me think there must be better ways than doing everything manually. I went on a search for a package that might help make things a bit less manual and more automatic.
I found this:
https://www.npmjs.com/package/np

To try it out I made a patch release with updated dependencies:
https://github.com/mesqueeb/copy-anything/releases

do you like it?
